stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: Ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: Use .NET Core SDK 6.0.x
            inputs:
              packageType: sdk
              version: 6.0.x

          - task: DotNetCoreCLI@2
            displayName: Restore Packages
            inputs:
              command: restore
              projects: $(Build.SourcesDirectory)/src/ContosoUniversity.csproj

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              arguments: --no-restore --configuration Release --verbosity normal
              projects: $(Build.SourcesDirectory)/src/ContosoUniversity.csproj

          - task: DotNetCoreCLI@2
            displayName: "Publish Web App"
            inputs:
              command: publish
              arguments: --no-restore --no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/WebApp
              projects: $(Build.SourcesDirectory)/src/ContosoUniversity.csproj
              publishWebProjects: false
              zipAfterPublish: true
              modifyOutputPath: false

          - task: PublishPipelineArtifact@1
            displayName: Publish Artifacts to Pipeline
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: webapp
              parallel: true
